name: flutter_card_flip_game
description: Find out under which card the Flutter logo is hiding.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  easy_debounce: ^2.0.2+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  page_flip_builder: ^0.1.3


dev_dependencies:
  build_runner:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1


flutter:
  uses-material-design: true
